const color = (name) => `rgb(var(--color-${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': color('surface'),
        'surface-dim': color('surface-dim'),
        'surface-bright': color('surface-bright'),
        'surface-container-lowest': color('surface-container-lowest'),
        'surface-container-low': color('surface-container-low'),
        'surface-container': color('surface-container'),
        'surface-container-high': color('surface-container-high'),
        'surface-container-highest': color('surface-container-highest'),
        'on-surface': color('on-surface'),
        'on-surface-variant': color('on-surface-variant'),
        'inverse-surface': color('inverse-surface'),
        'inverse-on-surface': color('inverse-on-surface'),
        'outline': color('outline'),
        'outline-variant': color('outline-variant'),
        'surface-tint': color('surface-tint'),
        'primary': color('primary'),
        'on-primary': color('on-primary'),
        'primary-container': color('primary-container'),
        'on-primary-container': color('on-primary-container'),
        'inverse-primary': color('inverse-primary'),
        'secondary': color('secondary'),
        'on-secondary': color('on-secondary'),
        'secondary-container': color('secondary-container'),
        'on-secondary-container': color('on-secondary-container'),
        'tertiary': color('tertiary'),
        'on-tertiary': color('on-tertiary'),
        'tertiary-container': color('tertiary-container'),
        'on-tertiary-container': color('on-tertiary-container'),
        'error': color('error'),
        'on-error': color('on-error'),
        'error-container': color('error-container'),
        'on-error-container': color('on-error-container'),
        'primary-fixed': color('primary-fixed'),
        'primary-fixed-dim': color('primary-fixed-dim'),
        'on-primary-fixed': color('on-primary-fixed'),
        'on-primary-fixed-variant': color('on-primary-fixed-variant'),
        'secondary-fixed': color('secondary-fixed'),
        'secondary-fixed-dim': color('secondary-fixed-dim'),
        'on-secondary-fixed': color('on-secondary-fixed'),
        'on-secondary-fixed-variant': color('on-secondary-fixed-variant'),
        'tertiary-fixed': color('tertiary-fixed'),
        'tertiary-fixed-dim': color('tertiary-fixed-dim'),
        'on-tertiary-fixed': color('on-tertiary-fixed'),
        'on-tertiary-fixed-variant': color('on-tertiary-fixed-variant'),
        'background': color('background'),
        'on-background': color('on-background'),
        'surface-variant': color('surface-variant'),
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'sidebar-width': '280px',
        'unit': '4px',
      },
    },
  },
  plugins: [],
}
