apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: EMS-Ops-frontend-ingress
  namespace: EMS-Ops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: EMS-Ops.local  # Replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: EMS-Ops-frontend-svc
                port:
                  number: 80
