apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - database.yaml
  - backend.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - monitoring.yaml
  - hpa.yaml
  - networkpolicy.yaml
