apiVersion: v1
kind: Service
metadata:
  name: ems-ops-frontend-svc
  namespace: ems-ops
  labels:
    app: ems-ops-frontend
    app.kubernetes.io/name: ems-ops-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ems-ops
spec:
  selector:
    app: ems-ops-frontend
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
